export const CATEGORIES = [
    {
        id: "food",
        label: "Food & Dining",
        icon: "coffee",
        iconSet: "Feather",
        color: "#F97316",
    },
    {
        id: "study",
        label: "Study",
        icon: "book",
        iconSet: "Feather",
        color: "#06B6D4",
    },
    {
        id: "shopping",
        label: "Shopping",
        icon: "shopping-bag",
        iconSet: "MaterialCommunityIcons",
        color: "#F59E0B",
    },
    {
        id: "transport",
        label: "Transport",
        icon: "car",
        iconSet: "Feather",
        color: "#3B82F6",
    },
    {
        id: "entertainment",
        label: "Entertainment",
        icon: "film",
        iconSet: "Feather",
        color: "#EC4899",
    },
    {
        id: "personal",
        label: "Personal Care",
        icon: "smile",
        iconSet: "Feather",
        color: "#14B8A6",
    },
    {
        id: "health",
        label: "Health",
        icon: "heart-pulse",
        iconSet: "MaterialCommunityIcons",
        color: "#EF4444",
    },
    {
        id: "bills",
        label: "Rent & Bills",
        icon: "home",
        iconSet: "Feather",
        color: "#8B5CF6",
    },
    {
        id: "travel",
        label: "Travel",
        icon: "send",
        iconSet: "Feather",
        color: "#10B981",
    },
    {
        id: "gifts",
        label: "Gifts & Donations",
        icon: "gift",
        iconSet: "Feather",
        color: "#D946EF",
    },
    {
        id: "other",
        label: "Other",
        icon: "more-horizontal",
        iconSet: "Feather",
        color: "#6B7280",
    },
];
